[tool.poetry]
name = "aiofix"
version = "0.1.0"
description = "A pure Python implementation of the FIX protocol"
authors = ["Rob Blackbourn <rob.blackbourn@googlemail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
aiofiles = "^0.4.0"
aiosqlite = "^0.9.0"

[tool.poetry.dev-dependencies]
pytest = "^4.2"
pytest-asyncio = "^0.10.0"
pytest-runner = "^4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
